CREATE TABLE USER_SCHEDULE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL ,
    schedule_id BIGINT NOT NULL ,
    FOREIGN KEY (user_id) REFERENCES USER(id),
    FOREIGN KEY (schedule_id) REFERENCES SCHEDULE(id)
)